version: '3.3'

services:
  socket-api:
    build:
      context: .
      # target: development
    volumes:
      - /usr/src/app/dist
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    # command: npm run start:dev
    command: npm run start:prod
    env_file:
      - .env
    # networks:
      # - socket-network
    networks:
      - default
    depends_on:
      - socket-redis
  socket-redis:
    image: redis:5
    ports:
      - 6379:6379
    # networks:
    #   - socket-network
    networks:
      - default
# networks:
#   socket-network:
volumes:
  socket-pgdata:
